### ISSUE TITLE
Campos Usuario que faltan

### ISSUE THREAD

**Issue by Lainezz** [Joakamakaka1/NewNocturnalHunters#1]
Recuerda que es obligatorio que la tabla usuarios tenga los campos username, password y roles. Estos campos son diferentes al campo nombre y demás que has puesto.

Ánimo!

**Comment by Joakamakaka1** [comment]
Hola
Lo solucione en cuanto me digiste.
He mantenido el campo de email, no se si deberia de quitarlo.

**Comment by Lainezz** [comment]
Está bien que lo mantengas. El campo rol te recomiendo que lo nombres "roles", porque si no, en el futuro te va a causar problemas.
